=== swtsoso/generator/code-generator/src/main/resources/generator-config.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT configuration (properties*,property*,classPathEntry*,jdbcConnection,templates,tables)>
<!ATTLIST configuration id ID #IMPLIED>

<!--
	加载配置文件：resource和url只能配置其中的一个
	resource 从类的路径中加载
	url 任意位置
-->
<!ELEMENT properties EMPTY>
<!ATTLIST properties 
	resource CDATA #IMPLIED
	url CDATA #IMPLIED>

<!ELEMENT property EMPTY>
<!ATTLIST property
  name CDATA #REQUIRED
  value CDATA #REQUIRED>

<!--
  加载jar或者class文件到classPath中
-->
<!ELEMENT classPathEntry EMPTY>
<!ATTLIST classPathEntry
  location CDATA #REQUIRED>

<!ELEMENT jdbcConnection (property*)>
<!ATTLIST jdbcConnection 
  driverClass CDATA #REQUIRED
  connectionURL CDATA #REQUIRED
  userId CDATA #REQUIRED
  password CDATA #REQUIRED>
 
<!--模版配置 -->
<!ELEMENT templates (template*)>
<!--
	所有模版文件公用属性
	overwrite 如果文件已存在是否重写，默认重写
	makeDirIfNotExist 如果存放目录不存在是否创建
	tplDirectory 模版文件的存放路径
-->
<!ATTLIST templates 
	overwrite (true|false) "true"
	makeDirIfNotExist (true|false) "true"
	tplDirectory CDATA #REQUIRED
>
<!ELEMENT template EMPTY>
<!--
	tplFile 模版文件名称
	targetDirectory 生成文件的存放路径
	保存的文件名为：文件名前缀+表名（首字母大写）+文件名后缀+"."+生成文件的类型
	fileType 生成文件的类型(后缀）
	fileNamePrefix 文件名前缀
	fileNameSuffix 文件名后缀
	
-->
<!ATTLIST template id CDATA #IMPLIED
	tplFile CDATA #REQUIRED
	targetDirectory CDATA #REQUIRED
	fileType CDATA #REQUIRED
	fileNamePrefix CDATA #IMPLIED
	fileNameSuffix CDATA #IMPLIED
>
<!--
	数据库中的表配置，多个值用","(英文)隔开，"*"匹配任意字符
	include 包含的表
	exclude 排除的表
	containsView 是否包含视图
	catalog schema 为java中DatabaseMetaData的getTables方法的参数
		schema oracle数据时为表用户
	forceBigDecimals 数值类型是否强制转化为BigDecimal类型
	生成规则：
		如果包含在 exclude中，不生成
		不在exclude中：
			如果include为空，生成
			如果include不为空
				包含在include中，生成
				不包含，不生成
-->
<!ELEMENT tables EMPTY>
<!ATTLIST tables 
	catalog CDATA #IMPLIED
	schema CDATA #IMPLIED
	containsView (true|false) "true"
	include CDATA #IMPLIED
	exclude CDATA #IMPLIED
	forceBigDecimals (true|false) "false"
>

=== swtsoso/generator/code-generator/src/test/resources/generatorConfig.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE configuration PUBLIC "-//xipintech.com//code generator//CN" "http://xipintech.com:8081/dtd/generator-config.dtd" >
<configuration>
	<property name="targetProject" value="D:/xpworkspace/xipin-projectframework"></property>
	<!-- 数据库驱动 -->
	<property name="driverClass" value="com.mysql.jdbc.Driver"></property>
	<!-- 数据库连接字符串 -->
	<property name="connectionURL" value="jdbc:mysql://127.0.0.1:3306/owl"></property>
	<!-- 数据库用户名 -->
	<property name="userName" value="root"></property>
	<!-- 数据库密码 -->
	<property name="password" value="123456"></property>
	<!-- 实体的包名 -->
	<property name="entityPackageName" value="com.xipin.projectframework.spi.log.domain"></property>
	<!-- mapper的包名 -->
	<property name="mapperPackageName" value="com.xipin.projectframework.dal.mapper.log"></property>
	<!-- service的包名 -->
	<property name="servicePackageName" value="com.xipin.projectframework.spi.log.service"></property>
	<!-- serviceImpl的包名 -->
	<property name="serviceImplPackageName" value="com.xipin.projectframework.log.service.impl"></property>
	<!-- controller的包名 -->
	<property name="controllerPackageName" value="com.xipin.projectframework.log.web.controller"></property>
	<!-- baseMapper的包名 -->
	<property name="baseMapperPackageName" value="com.xipin.base.dal.mapper"></property>
	<!-- baseService的包名 -->
	<property name="baseServicePackageName" value="com.xipin.base.service"></property>
	<!-- baseServiceImpl的包名 -->
	<property name="baseServiceImplPackageName" value="com.xipin.base.service.impl"></property>
	<!-- baseContoller的包名 -->
	<property name="baseContollerPackageName" value="com.xipin.base.web.controller"></property>
	
	<classPathEntry location="D:\xipin_work\repository\mybatis-generator\code-generator\code-generator\lib\mysql-connector-java-5.1.34-bin.jar"/>
	<jdbcConnection driverClass="${driverClass}" connectionURL="${connectionURL}" userId="${userName}" password="${password}" >
		<property name="remarksReporting" value="true"/>
	</jdbcConnection>
	<templates overwrite="true" makeDirIfNotExist="true" tplDirectory="D:\xipin_work\repository\mybatis-generator\code-generator\code-generator\src\main\resources\template2">
		<template targetDirectory="D:\xpworkspace\xipin-projectframework\xipin-projectframework-spi\src\main\java\com\xipin\projectframework\spi\log\domain" fileNamePrefix="" fileNameSuffix="" tplFile="model.ftl" fileType="java"></template>
		<template targetDirectory="D:\xpworkspace\xipin-projectframework\xipin-projectframework-spi\src\main\java\com\xipin\projectframework\spi\log\service" fileNamePrefix="" fileNameSuffix="Service" tplFile="service.ftl" fileType="java"></template>
		<template targetDirectory="D:\xpworkspace\xipin-projectframework\xipin-projectframework-service\src\main\java\com\xipin\projectframework\log\service\impl" fileNamePrefix="" fileNameSuffix="ServiceImpl" tplFile="serviceImpl.ftl" fileType="java"></template>
		<template targetDirectory="D:\xpworkspace\xipin-projectframework\xipin-projectframework-web\src\main\java\com\xipin\projectframework\log\web\controller" fileNamePrefix="" fileNameSuffix="Controller" tplFile="controller.ftl" fileType="java"></template>
		<template targetDirectory="D:\xpworkspace\xipin-projectframework\xipin-projectframework-dal\src\main\java\com\xipin\projectframework\dal\mapper\log" fileNamePrefix="" fileNameSuffix="Mapper" tplFile="jMapper.ftl" fileType="java"></template>
		<template targetDirectory="D:\xpworkspace\xipin-projectframework\xipin-projectframework-dal\src\main\resources\mapper\log" fileNamePrefix="" fileNameSuffix="Mapper" tplFile="mapper.ftl" fileType="xml"></template>
	</templates>
	<tables schema="test" forceBigDecimals="false" containsView="true" exclude="sys_*" include="log,bas_area"/>
</configuration>

=== swtsoso/generator/code-generator/src/test/resources/generatorConfig-bak.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE configuration PUBLIC "-//xipintech.com//code generator//CN" "http://xipintech.com:8081/dtd/generator-config.dtd" >
<configuration>
	<property name="targetProject" value="D:/temp"></property>
	<!-- 数据库驱动 -->
	<property name="driverClass" value="com.mysql.jdbc.Driver"></property>
	<!-- 数据库连接字符串 -->
	<property name="connectionURL" value="jdbc:mysql://localhost:3306/test"></property>
	<!-- 数据库用户名 -->
	<property name="userName" value="root"></property>
	<!-- 数据库密码 -->
	<property name="password" value="123456"></property>
	<!-- 实体的包名 -->
	<property name="entityPackageName" value="com.ydtf.entity"></property>
	<!-- mapper的包名 -->
	<property name="mapperPackageName" value="com.ydtf.mapper"></property>
	<!-- service的包名 -->
	<property name="servicePackageName" value="com.ydtf.service"></property>
	<!-- baseService的包名 -->
	<property name="baseServicePackageName" value="com.ydtf.base"></property>
	<!-- serviceImpl的包名 -->
	<property name="serviceImplPackageName" value="com.ydtf.service.impl"></property>
	<!-- baseMapper的包名 -->
	<property name="baseMapperPackageName" value="com.ydtf.base"></property>
	<classPathEntry location="D:\xipin_work\repository\mybatis-generator\code-generator\code-generator\lib\mysql-connector-java-5.1.34-bin.jar"/>
	<jdbcConnection driverClass="${driverClass}" connectionURL="${connectionURL}" userId="${userName}" password="${password}" >
		<property name="remarksReporting" value="true"/>
	</jdbcConnection>
	<templates overwrite="true" makeDirIfNotExist="true" tplDirectory="D:\xipin_work\repository\mybatis-generator\code-generator\code-generator\src\main\resources\template">
		<template targetDirectory="D:/tmp/test/src/com/ydtf/entity" fileNamePrefix="" fileNameSuffix="" tplFile="model.ftl" fileType="java"></template>
		<template targetDirectory="D:/tmp/test/src/com/ydtf/service" fileNamePrefix="" fileNameSuffix="Service" tplFile="service.ftl" fileType="java"></template>
		<template targetDirectory="D:/tmp/test/src/com/ydtf/service/impl" fileNamePrefix="" fileNameSuffix="ServiceImpl" tplFile="serviceImpl.ftl" fileType="java"></template>
		<template targetDirectory="D:/tmp/test/src/com/ydtf/mapper" fileNamePrefix="" fileNameSuffix="Mapper" tplFile="jMapper.ftl" fileType="java"></template>
		<template targetDirectory="D:/tmp/test/config/mapping" fileNamePrefix="" fileNameSuffix="Mapper" tplFile="mapper.ftl" fileType="xml"></template>
	</templates>
	<tables schema="test" forceBigDecimals="false" containsView="true" exclude="tsm*" include="goods,sec_kill"/>
</configuration>
